// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"week3_docker/internal/client/amo"
	"week3_docker/internal/client/unisender"
	"week3_docker/internal/handler"
	"week3_docker/internal/queue"
	"week3_docker/internal/repository/account"
	"week3_docker/internal/repository/contact"
	"week3_docker/internal/repository/integration"
	contact2 "week3_docker/internal/service/contact"
	"week3_docker/internal/store"
)

// Injectors from wire.go:

func InitializeServer() Server {
	client := amo.NewAmoClient()
	unisenderClient := unisender.NewClient()
	storeStore := store.NewStore()
	repository := account.NewAccountRepository(storeStore)
	contactRepository := contact.NewRepository(storeStore)
	integrationRepository := integration.NewRepository(storeStore)
	queueQueue := queue.NewQueue()
	service := contact2.NewService(client, unisenderClient, repository, contactRepository, integrationRepository, queueQueue)
	handlerHandler := handler.NewHandler(service)
	server := NewServer(service, handlerHandler)
	return server
}
