// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package worker

import (
	"week3_docker/internal/client/amo"
	"week3_docker/internal/client/unisender"
	"week3_docker/internal/queue"
	"week3_docker/internal/repository/account"
	"week3_docker/internal/repository/contact"
	"week3_docker/internal/repository/integration"
	contact2 "week3_docker/internal/service/contact"
	"week3_docker/internal/store"
)

// Injectors from wire.go:

func InitializeWorkerPool() WorkerPool {
	queueQueue := queue.NewQueue()
	client := amo.NewAmoClient()
	unisenderClient := unisender.NewClient()
	storeStore := store.NewStore()
	repository := account.NewAccountRepository(storeStore)
	contactRepository := contact.NewRepository(storeStore)
	integrationRepository := integration.NewRepository(storeStore)
	service := contact2.NewService(client, unisenderClient, repository, contactRepository, integrationRepository, queueQueue)
	workerPool := NewWorkerPool(queueQueue, service)
	return workerPool
}
